src/Entity/Room.php
<?php

namespace App\Entity;

use App\Repository\RoomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RoomRepository::class)
 */
class Room
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $capacity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvailable = true;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="rooms")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true,timestamp=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="rooms")
     */
    private $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }
}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Validator\Constraints\Length;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class,[
                'required'=>false,
                'label'=>false,
                'attr'=>[
                    'placeholder'=>'nom de la salle',
                    'class'=>'bg-info'
                ],
            ])
            ->add('capacity',IntegerType::class)
            ->add('city',TextType::class)
            ->add('description', TextareaType::class, [
                'required'=>false,
                'constraints'=>[
                    new NotBlank([
                        'message' => 'Merci d\'ajouter une description'
                    ]),
                    new Length([
                        'min'=>10,
                        'max'=>600,
                        'minMessage'=>'Le message doit faire au moin 10 caractere ',
                        'maxMessage'=>'Le message ne dois pas ecceder 600 car'

                    ])
                ]
            ])
            ->add('categories')


            // ->add('isAvailable')
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
            'translation_domain'=>'room_form'
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\Room;
use App\Form\RoomType;
use DateTimeInterface;
use App\Repository\RoomRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class RoomController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }


    /**
     * @Route("/room", name="room")
     */
    public function index(RoomRepository $RoomRepo): Response
    {

        $rooms = $RoomRepo->findAvailableRoom();

        return $this->render('room/index.html.twig', [
            'controller_name' => 'RoomController',
            'rooms'=>$rooms
        ]);
    }
  /**
     * @Route("/new", name="room.add", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     * @return Response
     */

    public function new(Request $request) : Response
    {
        $dateImmutable = \DateTime::createFromFormat('Y-m-d H:i:s', strtotime('now')); # also tried using \DateTimeImmutable

        $room = new Room();
        $room->setUser($this->security->getUser());
        $room->setCreatedAt(new DateTime());
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager =$this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();


            $this->addFlash('success', 'la salle a bine etait enregistrer');
            return $this->redirectToRoute('room');
        }
        return $this->render('room/new.html.twig',[
            'room'=>$room,
            'form'=>$form->createView()
        ]);
    }


/**
     * @Route("/{id}/edit",name="room.edit", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Room $room) : Response
    {       
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $room->setUpdatedAt(new DateTime());
            // dd($room);
            $entityManager = $this->getDoctrine()->getManager();
            // dd($entityManager);
            // $entityManager->persist($room);
            $entityManager->flush();
            $this->addFlash('success','La salle a bien été modifée');
            return $this->redirectToRoute('room');
        }
        return $this->render('room/edit.html.twig',[
            'room'=>$room,
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("/{id}",name="room.delete", methods={"DELETE"})
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function delete(Request $request, Room $room) : Response
    {
        if($this->isCsrfTokenValid('delete'.$room->getId(),$request->request->get('_token'))){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();

            $this->addFlash('success','La salle a bien été supprimée');
            return $this->redirectToRoute('room');
        }
    }
}

templates/room/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une salle{% endblock %}

{% block body %}

<div class="container">
    <h1>Ajouter une salle</h1>
    {# {{form(form)}} #}
    {{form_start(form)}}
    <div class="row">
        <div class="col-md-6">{{form_row(form.name)}}</div>
        <div class="col-md-6">{{form_row(form.description)}}</div>
    </div>
    <div class="row">
        <div class="col-md-4">{{form_row(form.capacity)}}</div>
        <div class="col-md-4">{{form_row(form.city)}}</div>
    </div>

    <div class="row">
        <div class="col-md-4">{{form_row(form.categories)}}</div>
    </div>

    <div class="row">
        <button class="btn btn-primary col-5">Valider</button>
    {{form_end(form)}}
        <br>    
    <a class="btn btn-primary offset-1 col-5" href="{{path('room')}}">Retour</a>
    </div>

</div>
{% endblock %} 

templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue | Accueil{% endblock %}

{% block body %}

    <div class="container">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success mb-0 text-center">
                {{message}}
            </div>
        {% endfor %}

        <h1>Salles</h1>
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <a class="btn btn-primary" href="{{path('room.add')}}">Ajouter une salle</a>
        {% endif %}

        <table class="table">
            <thead>
                <tr>
                    <th scope='col'>#</th>
                    <th scope='col'>Name</th>
                    <th scope='col'>City</th>
                    <th scope='col'>Description</th>
                    <th scope='col'>Disponibilité</th>
                    <th scope='col'>crée le </th>

                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        <th scope='col'>Action</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for room in rooms %}
                    <tr>
                        <td>{{room.id}}</td>
                        <td>{{room.name}}</td>
                        <td>{{room.city}}</td>
                        <td>{{room.description | length > 100 ? room.description | slice (0,100) ~ '...' : room.description}}</td>
                        <td>{{room.isAvailable}}</td>
                        <td>{{room.createdAt|date('Y-m-d')}}</td>

                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            <td>
                                <a class="btn btn-primary" href="{{path('room.edit', {id:room.id})}}">Editer</a>
                                <form method="post" action="{{path('room.delete', {id:room.id})}}" style="display: inline-block" onsubmit="return confirm('Confirmer la suppression')">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{csrf_token('delete'~room.id)}}">
                                    <button class="btn btn-danger">Supprimer </button>
                                </form>
                            </td>
                            


                        {% endif %}

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une salle{% endblock %}

{% block body %}

<div class="container">
    <h1>Ajouter une salle</h1>
    {# {{form(form)}} #}
    {{form_start(form)}}
    <div class="row">
        <div class="col-md-6">{{form_row(form.name)}}</div>
        <div class="col-md-6">{{form_row(form.description)}}</div>
    </div>
    <div class="row">
        <div class="col-md-4">{{form_row(form.capacity)}}</div>
        <div class="col-md-4">{{form_row(form.city)}}</div>
    </div>
        <div class="row">
        <div class="col-md-4">{{form_row(form.categories)}}</div>
    </div>

    <div class="row">
        <button class="btn btn-primary col-5">Valider</button>
    {{form_end(form)}}
        <br>
    <a class="btn btn-primary offset-1 col-5" href="{{path('room')}}">Retour</a>
    </div>

</div>
{% endblock %} 